### PR TITLE
Fix black screen when completing a snapshot transition on iOS 13

### PR DESCRIPTION
**Pull request by colinhumber**

### CODE REVIEW

**Comment by colinhumber** [comment]
Fixes #11

**Comment by cgossain** [comment]
Relating to code debt, Apple recommends that the deployment targets should be set to the most recent version of the previous major release. This is why the deployment target was set to 10.3.

Therefore, I would prefer keeping the deployment target at 10.3. Thoughts?

**Comment by colinhumber** [comment]
I was thinking since there are no APIs in use that specifically require a 10.3 deployment target keeping it at 10.0 doesn’t add any development overhead. But it’s totally your call. 

We can always branch and use a custom deployment target as needed.

**Comment by cgossain** [comment]
True, but I would prefer keeping expectations low just in case I do want to bring in APIs from 10.3. This way, the update would not be a breaking change.

**Comment by colinhumber** [comment]
Yup, no problem. I'll revert the deployment target change. We can maintain our own branch.

**Comment by cgossain** [comment]
Perfect. Thanks!

**Pull request merged**
