### PR TITLE
Update podspec version

### PR DESCRIPTION
**Pull request by Bruno-Furtado**
Update podspec version with Swift 4.2 modifications.

### CODE REVIEW

**Comment by Bruno-Furtado** [comment]
Would you create a new pod version (0.6.3) with the Swift 4.2?
Thanks.

**Comment by cgossain** [comment]
Hi Bruno, have you made any of the code changes in this PR? If not, I should be able to do this sometime tomorrow.

**Comment by Bruno-Furtado** [comment]
Hi @cgossain, 

No. It's not necessary code changes.
Everything works fine on Swift 4.2.
It's only necessary to create a tag to use the new version with CocoaPods.

Thanks.

**Comment by cgossain** [comment]
I'll push to the cocoapods repo momentarily.

**Comment by cgossain** [comment]
@Bruno-Furtado Version 0.6.3 has been pushed to the CocoaPods trunk.

**Pull request merged**
